#ddev-generated

http:
  routers:
    temporalio-ui:
      entrypoints:
        - http-443
      rule: Host(`HOST_REPLACE_THIS`)
      service: "NAME_REPLACE_THIS-temporalio-ui"
      ruleSyntax: v3
      tls: true
      priority: 100000
  services:
    NAME_REPLACE_THIS-temporalio-ui:
      loadbalancer:
        servers:
          - url: http://ddev-NAME_REPLACE_THIS-temporalio-ui:8080
